apiVersion: v1
kind: Service
metadata:
  name: flask-web
  namespace: flask-prod
  # Removemos annotations do Google Cloud aqui
spec:
  type: ClusterIP
  selector:
    app: flask-web
  ports:
    - name: http
      port: 80
      targetPort: 8080
