name: CI - Build & Push image (GHCR)

on:
  push:
    branches: [ main, rolling, teste ]
    paths:
      - 'app/**'
      - 'Dockerfile'
      - '.github/workflows/build-and-push.yml'
  pull_request:
    branches: [ main ]
    paths:
      - 'app/**'
      - 'Dockerfile'
      - '.github/workflows/build-and-push.yml'

permissions:
  contents: write
  packages: write

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: Amsatnaf
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/amd64,linux/arm64
          # Regra: Faz push se for main, rolling OU teste
          push: ${{ github.event_name == 'push' && (github.ref == 'refs/heads/main' || github.ref == 'refs/heads/rolling' || github.ref == 'refs/heads/teste') }}
          tags: |
            ${{ github.ref == 'refs/heads/main' && 'ghcr.io/amsatnaf/flask-ola-mundo:latest' || '' }}
            ghcr.io/amsatnaf/flask-ola-mundo:${{ github.sha }}

      - name: Update Kubernetes Manifest
        # Executa atualização de manifesto se for main ou teste
        if: github.event_name == 'push' && (github.ref == 'refs/heads/main' || github.ref == 'refs/heads/teste')
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"

          # LÓGICA DE PASTAS SEPARADAS
          if [[ "${{ github.ref }}" == "refs/heads/main" ]]; then
            echo "Branch Main detectada: Atualizando pasta PROD"
            FILE_PATH="prod/deployment.yaml"
          elif [[ "${{ github.ref }}" == "refs/heads/teste" ]]; then
            echo "Branch Teste detectada: Atualizando pasta TESTE"
            FILE_PATH="teste/deployment.yaml"
          fi

          echo "Alvo: $FILE_PATH"

          # Verifica se o arquivo existe para evitar erro
          if [ -f "$FILE_PATH" ]; then
             # Atualiza a tag da imagem com o SHA do commit
             sed -i "s|image: ghcr.io/amsatnaf/flask-ola-mundo:.*|image: ghcr.io/amsatnaf/flask-ola-mundo:${{ github.sha }}|g" $FILE_PATH
             
             git add $FILE_PATH
             git commit -m "chore(ci): update image tag to ${{ github.sha }} [skip ci]"
             git push
          else
             echo "ERRO: O arquivo $FILE_PATH não existe nesta branch. Verifique a estrutura de pastas."
             exit 1
          fi
